# Generated by Django 2.1 on 2021-02-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='roll_no',
            field=models.CharField(default='BCT074047', max_length=9),
        ),
    ]
