# Generated by Django 2.1 on 2021-02-22 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_roll_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='roll_no',
        ),
    ]
