# Generated by Django 2.1 on 2021-02-27 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(default='BCT074047', max_length=9)),
                ('resume', models.FileField(blank=True, default='infosec/Prerits_Resume.pdf', upload_to='infosec')),
                ('github_link', models.CharField(blank=True, default='github.com', max_length=200)),
                ('facebook_link', models.CharField(blank=True, default='facebook.com', max_length=200)),
                ('phone_no', models.IntegerField(default=9842611149)),
                ('father_name', models.CharField(default='Prem Sagar Bhandari', max_length=250)),
                ('mother_name', models.CharField(default='Bimala Bhandari', max_length=250)),
                ('guardian_no', models.IntegerField(default=9845047706)),
                ('address', models.CharField(default='Bharatpur', max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
