# Generated by Django 2.1 on 2021-02-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infosec', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='resume',
            field=models.ImageField(upload_to='infosec'),
        ),
    ]
