# Generated by Django 2.1 on 2021-02-27 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infosec', '0002_auto_20210227_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='user',
        ),
    ]
