# Generated by Django 2.1 on 2021-02-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infosec', '0003_auto_20210220_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='facebook_link',
            field=models.CharField(default='facebook.com', max_length=200),
        ),
        migrations.AddField(
            model_name='information',
            name='github_link',
            field=models.CharField(default='github.com', max_length=200),
        ),
        migrations.AddField(
            model_name='information',
            name='linkedin_link',
            field=models.CharField(default='linkedin.com', max_length=200),
        ),
        migrations.AddField(
            model_name='information',
            name='website',
            field=models.CharField(default='www.studentservice.com', max_length=200),
        ),
    ]
