# Generated by Django 2.1 on 2021-02-27 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infosec', '0004_information_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
