# Generated by Django 2.1 on 2021-02-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infosec', '0005_auto_20210222_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='resume',
            field=models.FileField(default='default.jpg', upload_to='infosec'),
        ),
    ]
