# Generated by Django 2.1 on 2021-03-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infosec', '0006_auto_20210227_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='roll_no',
            field=models.CharField(default='BCT074000', max_length=9),
        ),
    ]
