# Generated by Django 2.1 on 2021-02-22 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infosec', '0007_auto_20210222_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='resume',
            field=models.FileField(default='infosec/Prerits_Resume.pdf', upload_to='infosec'),
        ),
        migrations.AlterField(
            model_name='information',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
