# Generated by Django 2.1 on 2020-04-04 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='Prerit Bhandari', max_length=100)),
                ('faculty', models.CharField(choices=[('BCT', 'Computer'), ('BCE', 'Electrical'), ('BEX', 'Electronics')], max_length=10)),
                ('roll_no', models.CharField(default='074047', max_length=6)),
                ('total_annual_fee', models.IntegerField(default=1000000)),
                ('paid_annual_fee', models.IntegerField()),
                ('remaining_annual_fee', models.IntegerField()),
                ('last_annual_date_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_monthly_fee', models.IntegerField(default=5000)),
                ('paid_monthly_fee', models.IntegerField()),
                ('remaining_monthly_fee', models.IntegerField()),
                ('last_monthly_date_modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
