# Generated by Django 2.1 on 2021-03-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='thumbnail',
            field=models.ImageField(blank=True, default='media/thumbnails/bookdefault.jpg', upload_to='media/thumbnails/'),
        ),
    ]
