# Generated by Django 2.1 on 2021-03-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addfee',
            name='roll_no',
            field=models.CharField(default='BCT074000', max_length=9),
        ),
    ]
