# Generated by Django 2.1 on 2021-02-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210220_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='details',
            field=models.TextField(default='No Details'),
        ),
    ]
