# Generated by Django 2.1 on 2021-03-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210303_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
