# Generated by Django 2.1 on 2021-02-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210220_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='details',
            field=models.CharField(default='No Details', max_length=100),
        ),
    ]
