# Generated by Django 2.1 on 2021-02-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210220_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='details',
            field=models.CharField(default='No Details', max_length=30),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
